### ISSUE TITLE
Wrong statusses are shown:

### ISSUE THREAD

**Issue by harbingerofme** [dude22072/PokeStats#1]
Previous' guide to pokémon status conditions: pokéstat shows / actual condidion is; poison / sleep; burn / poison; frozen / burn; paralyzed / frozen; badly poisoned / paralyzed

**Comment by dude22072** [comment]
Easy fix could be to change what the LUA outputs.
The following LUA outputs for status is what pokestats displays:
3 - Sleep
4 - Poison
5 - Burn
6 - Frozen
7 - Paralisis

**Comment by dude22072** [comment]
Fix implemented by f00barbob
